name: AutoIssueBot
on: push

jobs:
  send_to_gemini:
    env: 
      GOOGLE_API_KEY : ${{ secrets.GOOGLE_API_KEY }}
    environment: send_to_gemini
    runs-on: ubuntu-latest
    outputs:
      file-name: ${{ steps.get-app-file.outputs.file }}
    steps:

      - name: Get Code
        uses: actions/checkout@v3


      - name: Get code
        id: get-app-file
        run: |
          file=$(find dist/assets/ -type f -name 'app.*' | head -n 1)
          echo "file=$file" >> "$GITHUB_OUTPUT"      
      

      - name: Print code
        run: echo "File ${{ steps.get-app-file.outputs.file }}"